services:
  # ollama:
  #   build: ./ollama
  #   container_name: rag-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./ollama/data:/root/.ollama
  #   environment:
  #     - OLLAMA_VULKAN=1

  qdrant:
    image: qdrant/qdrant
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/usr/src/qdrant/storage

  n8n:
    build: ./n8n
    container_name: rag-n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678/
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_BLOCK_SVC_REGISTRATION_EMAIL=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_BLOCK_NODES_IMPORT_CHECK=true
      - N8N_FILESYSTEM_ALLOWED_PATHS=/home/node/.n8n-files
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n/data:/home/node/.n8n
      - "${PATH_DATA}:/home/node/.n8n-files"
      - "${PATH_DATA_ORIG}:/home/node/.n8n-files"
    depends_on:
      - qdrant

  prompt-ui:
    build:
      context: ./prompt-ui
      target: dev
    container_name: rag-prompt-ui
    ports:
      - "8088:8088"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./prompt-ui:/app
      - /app/node_modules
    depends_on:
      - n8n

volumes:
  qdrant_storage:
    external: true

networks:
  default:
    name: n8n-rag-net
